// Library exports for testing and external use

// Pure modules — always available, including in test mode
pub mod acp_client;
pub mod activity_tracker;
pub mod agent_presets;
pub mod agent_sessions;
pub mod app_launcher;
pub mod app_log;
pub mod auto_steering;
pub mod chunk_batcher;
pub mod computer_control;
pub mod config;
pub mod config_export;
pub mod config_migrations;
pub mod context_rules;
pub mod crash_recovery;
pub mod ephemeral_session;
pub mod error;
pub mod events;
pub mod extensions;
pub mod hotkey_norm;
pub mod i18n;
pub mod link_metadata_cache;
pub mod lock_ext;
pub mod logger;
pub mod mcp_json_rpc;
pub mod mcp_registration;
pub mod ollama;
pub mod os;
pub mod panic_handler;
pub mod permission_audit;
pub mod process_manager;
pub mod session_titler;
pub mod slash_format;
pub mod startup;
pub mod steering_io;
pub mod webview_recovery;
pub mod window_labels;

// Tauri-dependent modules
pub mod automation;
pub mod commands;
pub mod event_targets;
pub mod setup;
pub mod state;
pub mod telemetry;
pub mod tray;
pub mod updater;
